courses/urls.py
from django.urls import path, re_path


from .views import (course_list, course_detail, text_detail, quiz_detail,
                    quiz_create, quiz_edit, create_question, edit_question,
                    answer_question, courses_by_teacher, search_courses)

urlpatterns = [
    path('', course_list, name='course_list'),
    re_path(r'by/(?P<teacher>[-\w]+)/$', courses_by_teacher, name='courses_by_teacher'),
    path('<int:pk>', course_detail, name='course_detail'),
    # path('<int:course_pk>/steps/<int:step_pk>', step_detail, name='step_detail'),
    path(r'search/', search_courses, name="search_courses"),
    path('<int:course_pk>/texts/<int:step_pk>', text_detail, name='text_detail'),
    path('<int:course_pk>/quizzes/<int:step_pk>', quiz_detail, name='quiz_detail'),
    path('<int:course_pk>/create_quiz', quiz_create, name='create_quiz'),
    path('<int:course_pk>/edit_quiz/<int:step_pk>', quiz_edit, name='edit_quiz'),
    re_path(r'^(?P<quiz_pk>\d+)/create_question/(?P<question_type>mc|tf)/$',
            create_question, name="create_question"),
    re_path(r'^(?P<quiz_pk>\d+)/edit_question/(?P<question_pk>\d+)/$',
            edit_question, name="edit_question"),
    re_path(r'^(?P<question_pk>\d+)/answer_question/$',
            answer_question, name="answer_question"),
]

learning_site/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('courses/', include(('courses.urls', 'courses'), namespace='courses')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += re_path(r'^__debug__/', include(debug_toolbar.urls)),

urlpatterns += staticfiles_urlpatterns()

courses/models.py
import math

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


STATUS_CHOICES =  (
    ('i', 'In Progress'),
    ('r', 'In Review'),
    ('p', 'Published')
)


class Course(models.Model):
    
    title = models.CharField(max_length=200)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    teacher = models.ForeignKey(User, on_delete='models.CASCADE')
    subject = models.CharField(max_length=100, default='')
    published = models.BooleanField(default=False)
    status  = models.CharField(max_length=1, choices=STATUS_CHOICES, default='i')

    def __str__(self):
        return self.title
    
    def time_to_complete(self):
        from courses.templatetags.course_extras import time_estimate
        return '{} min'.format(time_estimate(len(self.description.split())))


class Step(models.Model):

    title = models.CharField(max_length=200)
    description = models.TextField()
    # content = models.TextField(blank=True, default='')
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course, on_delete='models.CASCADE')

    class Meta:
        abstract = True
        ordering = ['order']

    def __str__(self):
        return self.title


class Text(Step):
    content = models.TextField(blank=True, default='')

    def get_absolute_url(self):
        return reverse("courses:text_detail",
                       kwargs={"course_pk": self.course_id, "step_pk": self.pk})
    


class Quiz(Step):
    total_questions = models.IntegerField(default=4)
    times_taken = models.IntegerField(default=0, editable=False)

    class Meta:
        verbose_name_plural = "Quizzes"

    def get_absolute_url(self):
        return reverse("courses:quiz_detail",
                       kwargs={"course_pk": self.course_id, "step_pk": self.pk})
    
    def number_correct_needed(self):
        return '{}/{}'.format(math.ceil(self.total_questions * 0.7),
                              self.total_questions)


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete='models.CASCADE')
    order = models.IntegerField(default=0)
    prompt = models.TextField()

    class Meta:
        ordering = ['order',]
    
    def __str__(self):
        return self.prompt
    
    def get_absolute_url(self):
        return self.quiz.get_absolute_url()


class MultipleChoiceQuestion(Question):
    shuffle_answer = models.BooleanField(default=False)


class TrueFalseQuestion(Question):
    pass


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete='models.CASCADE')
    order = models.IntegerField(default=0)
    text = models.CharField(max_length=200)
    correct = models.BooleanField(default=False)

    class Meta:
        ordering = ['order',]
    
    def __str__(self):
        return self.text

courses/forms.py
from django import forms

from . models import Quiz, MultipleChoiceQuestion, TrueFalseQuestion, Answer


class QuizForm(forms.ModelForm):
    
    class Meta:
        model = Quiz
        fields = [
            'title',
            'order',
            'description',
            'total_questions'
        ]


class TrueFalseQuestionForm(forms.ModelForm):

    class Meta:
        model = TrueFalseQuestion
        fields = [
            'order',
            'prompt'
        ]


class MultipleChoiceQuestionForm(forms.ModelForm):

    class Meta:
        model = MultipleChoiceQuestion
        fields = [
            'order',
            'prompt',
            'shuffle_answer'
        ]


class AnswerQuestionForm(forms.ModelForm):

    class Meta:
        model = Answer
        fields = [
            'order',
            'text',
            'correct'
        ]

courses/views.py
from itertools import chain

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from django.db.models import Count, Q, Sum
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from .models import Course, Text, Quiz, Question
from .forms import QuizForm, TrueFalseQuestionForm, MultipleChoiceQuestionForm, AnswerQuestionForm


def course_list(request):
    # courses = Course.objects.all()
    courses = Course.objects.filter(
        published=True
    ).annotate(total_steps=Count(
        'text', distinct=True)+Count('quiz', distinct=True)
    )
    total = courses.aggregate(total=Sum('total_steps'))
    email = 'pwalukagga@gmail.com'
    ctx = {
        "courses": courses,
        "total": total,
        "email": email,
    }
    return render(request, 'courses/course_list.html', ctx)


def courses_by_teacher(request, teacher):
    courses = Course.objects.filter(teacher__username=teacher, published=True)
    email = 'pwalukagga@gmail.com'
    ctx = {
        "courses": courses,
        "email": email,
    }
    return render(request, 'courses/course_list.html', ctx)


def course_detail(request, pk):
    # course = Course.objects.get(pk=pk)
    # course = get_object_or_404(Course, pk=pk, published=True)
    try:
        course = Course.objects.prefetch_related(
            'quiz_set', 'text_set', 'quiz_set__question_set'
        ).get(pk=pk, published=True)
    except Course.DoesNotExist:
        raise Http404
    else:
        steps = sorted(chain(course.text_set.all(), course.quiz_set.all()),
                    key=lambda step: step.order)
    ctx = {
        "course": course,
        "steps": steps,
    }
    return render(request, 'courses/course_detail.html', ctx)


def search_courses(request):
    term = request.GET.get('q')
    # courses = Course.objects.filter(title__icontains=term, published=True)
    courses = Course.objects.filter(Q(title__icontains=term) |
                                    Q(description__icontains=term),
                                    published=True)
    email = 'pwalukagga@gmail.com'
    ctx = {
        "courses": courses,
        "email": email,
    }
    return render(request, 'courses/course_list.html', ctx)


# def step_detail(request, course_pk, step_pk):
#     step = get_object_or_404(Step, course_id=course_pk, pk=step_pk)
#     ctx = {
#         "step": step,
#     }
#     return render(request, 'courses/step_detail.html', ctx)


def text_detail(request, course_pk, step_pk):
    step = get_object_or_404(Text, course_id=course_pk, pk=step_pk,
                             course__published=True)
    ctx = {
        "step": step,
    }
    return render(request, 'courses/text_detail.html', ctx)


def quiz_detail(request, course_pk, step_pk):
    # step = get_object_or_404(Quiz, course_id=course_pk, pk=step_pk,
    #                          course__published=True)
    try:
        step = Quiz.objects.select_related(
            'course'
        ).prefetch_related(
            'question_set',
            'question_set__answer_set',
        ).get(
            course_id=course_pk, pk=step_pk, course__published=True
        )
    except Quiz.DoesNotExist:
        raise Http404
    else:
        ctx = {
            "step": step,
        }
        return render(request, 'courses/quiz_detail.html', ctx)


@login_required
def quiz_create(request, course_pk):
    course = get_object_or_404(Course, pk=course_pk, course__published=True)
    form = QuizForm()

    if request.method == "POST":
        form = QuizForm(request.POST)
        
        if form.is_valid():
            quiz = form.save(commit=False)
            quiz.course = course
            quiz.save()
            messages.add_message(request, messages.SUCCESS,
                         "Quiz to the question has been created!")
            return redirect(reverse('courses:quiz_detail', args=[quiz.course.pk, quiz.pk]))
    cxt = {
        "form": form,
        "course": course,
    }
    return render(request, "courses/quiz_form.html", cxt)


@login_required
def quiz_edit(request, course_pk, step_pk):
    quiz = get_object_or_404(Quiz, pk=step_pk, course_id=course_pk,
                             course__published=True)
    form = QuizForm(instance=quiz)

    if request.method=="POST":
        form = QuizForm(instance=quiz, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Quiz has been updated")
            return redirect(reverse('courses:edit_quiz', args=[quiz.course.pk, quiz.pk]))

    cxt = {
        "form": form,
        "course": quiz.course,
    }
    return render(request, "courses/quiz_form.html", cxt)


@login_required
def create_question(request, quiz_pk, question_type):
    quiz = get_object_or_404(Quiz, pk=quiz_pk, course__published=True)
    
    if question_type == "tf":
        form_class = TrueFalseQuestionForm
    else:
        form_class = MultipleChoiceQuestionForm
    
    form = form_class()

    if request.method == "POST":
        form = form_class(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.quiz = quiz
            question.save()
            messages.success(request, "Question added!")
            # return redirect(reverse(quiz.get_absolute_url()))
            return HttpResponseRedirect(quiz.get_absolute_url())
    cxt = {
        "quiz": quiz,
        "form": form,
    }
    return render(request, "courses/question_form.html", cxt)


@login_required
def edit_question(request, question_pk, quiz_pk):
    question = get_object_or_404(Question, pk=question_pk, quiz_id=quiz_pk)

    if hasattr(question, 'truefalsequestion'):
        question = question.truefalsequestion
        form_class = TrueFalseQuestionForm
    else:
        question = question.multiplechoicequestion
        form_class = MultipleChoiceQuestionForm
    form = form_class(instance=question)

    if request.method == "POST":
        form = form_class(instance=question, data=request.POST)
        form.save()
        messages.success(request, "Question has been updated")
        return HttpResponseRedirect(question.quiz.get_absolute_url())
    
    cxt = {
        "form": form,
        "quiz": question.quiz,
    }
    return render(request, "courses/question_form.html", cxt)


@login_required
def answer_question(request, question_pk):
    question = get_object_or_404(Question, pk=question_pk)
    form = AnswerQuestionForm()

    if request.method == "POST":
        form = AnswerQuestionForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.question = question
            answer.save()
            messages.success(request, "Answer added!")
            return HttpResponseRedirect(question.get_absolute_url())
    cxt = {
        "form": form,
        "question": question
    }
    return render(request, "courses/answer_form.html", cxt)

courses/templates/courses/answer_form.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}New Answer | {{ question.prompt }} | {{ question.quiz.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:course_detail' pk=question.quiz.course.pk %}">{{ question.quiz.course.title }}</a></li>
    <li><a href="{% url 'courses:quiz_detail' course_pk=question.quiz.course.pk step_pk=question.quiz.pk %}">{{ question.quiz.title }}</a></li>
    <li>{{ question.prompt }}</li>
{% endblock %}

{% block content %}
    <div class="row columns">
    {{ block.super }}
    <h1>Add Answer</h1>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="button" value="Save">
    </form>
</div>
{% endblock %}

courses/templates/courses/course_detail.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}{{ course.title }}{% endblock %}

{% block content %}
    <div class="row columns">
        {{ block.super }}
        <article>
            <h1 class="">{{ course.title }}</h1>

            <div class="callout secondary">
                {{ course.description|markdown_to_html }}
            </div>

            <dl>
                {% for step in steps %}
                    <dt>
                        <a href="{{ step.get_absolute_url }}">{{ step.title }}</a>
                    </dt>
                    <dd>{{ step.description|markdown_to_html }}</dd>
                    {% if step.question_set.all %}
                        <dt>Total Questions</dt>
                        <dd>{{ step.question_set.count }}</dd>
                    {% endif %}
                {% empty %}
                    <p>This course has no steps yet</p>
                {% endfor %}
            </dl>
        </article>
        {% if user.is_authenticated %}
            <hr>
            <a href="{% url 'courses:create_quiz' course_pk=course.id %}" class="button">New Quiz</a>
        {% endif %}
    </div>
{% endblock %}


{% comment %}
<!-- {% extends 'base.html' %}
{% load course_extras %}

{% block title %}
    {{ course.title }}-{{ block.super }}
{% endblock %}

{% block content %}
    {% if course %}
        <article>
            <h2>{{ course.title }}</h2>
            <p>{{ course.description|markdown_to_html }}</p>

            <h2>{{ course.step_set.count }} Step{{ course.step_set.count|pluralize }} in this course</h2>
            -- {% for step in course.step_set.all %}
                <h3><a href="{% url 'courses:step_detail' step.course.pk step.pk %}">{{ step.title }}</a></h3>
                {{ step.description|markdown_to_html }}
            {% empty %}
                <p>This course has no steps yet</p>
            {% endfor %} --
            {% for step in steps %}
                <h3><a href="{{ step.get_absolute_url }}">{{ step.title }}</a></h3>
                {{ step.description|markdown_to_html }}
            {% empty %}
                <p>This course has no steps yet</p>
            {% endfor %}
        </article>
    {% endif %}
{% endblock %} -->
{% endcomment %}

courses/templates/courses/course_list.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}All{% endblock %}

{% block content %}
    <div class="row columns">
        {{ block.super }}
    </div>
    <div class="row">
        <p><strong>Total number of Quiz and Text steps: </strong>{{ total.total }}</p>
        {%  for course in courses %}
            <div class="small-6 columns">
                <div class="callout">
                    <h5><a href="{% url 'courses:course_detail' pk=course.pk %}">{{ course.title }}</a></h5>
                    <div class="card-copy">
                        {{ course.description|markdown_to_html }}
                        <br>
                        {% if course.total_steps %}
                            <p><strong>Steps: </strong>{{ course.total_steps }}</p>
                        {% endif %}
                    </div>
                </div>
                <div>Created on: {{ course.created_at|date:"F j, Y" }}</div>
            </div>

            {% if forloop.counter|divisibleby:"2" %}
                </div>
                <div class="row">
            {% endif %}
        {% empty %}
            <p>No courses here yet</p>
        {% endfor %}
        <hr>
        <div class="row">
            <p>Do not miss out on our latest course: {% newest_course %}</p>
            Have any questions contact us: {{ email|urlize }}
        </div>
    </div>
{% endblock %}


{% comment %}
<!-- {% extends "base.html" %}
{% load static from staticfiles %}
{% load course_extras %}

{% block static %}
    <link href="{% static 'courses/css/courses.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}
    Courses-{{ block.super }}
{% endblock %}

{% block content %}
    <div class="cards">
        {% for course in courses %}
            <div class="card">
                <header>
                    <a href="{% url 'courses:course_detail' course.pk %}">{{ course.title }}</a>
                </header>
                <div class="card-copy">
                    <p>{{ course.description }}</p>
                </div>
                <div>Created on: {{ course.created_at|date:"F j, Y" }}</div>
            </div>
        {% endfor %}
    </div>
    <p>Do not miss out on our latest course: {% newest_course %}</p>
    Have any questions contact us: {{ email|urlize }}
{% endblock %} -->
{% endcomment %}

courses/templates/courses/course_nav.html
<div>
    {% for course in courses %}
       {% comment <a href="{% url 'courses:course_detail' pk=course.pk %}">{{ course.title }}</a> %}{% endcomment %}
       <a href="{% url 'courses:course_detail' pk=course.id %}">{{ course.title }}</a>
    {% endfor %}
</div>

courses/templates/courses/layout.html
{% extends "base.html" %}

{% block title %}Courses | {{ block.super }}{% endblock %}

{% block content %}
    {{ block.super }}
    <ul class="breadcrumbs">
        {% comment %}<!-- <li><a href="{% url 'home' %}">Home</a></li> -->{% endcomment %}
        <li><a href="{% url 'courses:course_list' %}">Courses</a></li>
        {% block breadcrumbs %}{% endblock %}
    </ul>
{% endblock %}

courses/templates/courses/question_form.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}New question for {{ quiz.title }} | {{ quiz.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:course_detail' pk=quiz.course.pk %}">{{ quiz.course.title }}</a></li>
    <li><a href="{% url 'courses:quiz_detail' course_pk=quiz.course.pk step_pk=quiz.pk %}">{{ quiz.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row columns">
    {{ block.super }}
    <h2>{{ form.instance.prompt|default:"Make a new question" }}</h2>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="button" value="Save">
    </form>
    {% if user.is_authenticated and form.instance.pk %}
        <hr>
        <a href="{% url 'courses:answer_question' question_pk=form.instance.pk %}" class="button">Add Answer</a>
    {% endif %}
</div>
{% endblock %}

courses/templates/courses/quiz_detail.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}{{ step.title }} | {{ step.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:course_detail' pk=step.course.pk %}">{{ step.course.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row columns">
        <article>
            {{ block.super }}
            <h1>{{ step.title }}</h1>
            <ul class="no-bullet">
                {% for question in step.question_set.all %}
                    <li>
                        <h3>
                            {{ question.prompt }} | 
                            {% if user.is_authenticated %}
                                <a href="{% url 'courses:edit_question' question_pk=question.pk quiz_pk=step.pk %}">
                                    <small>Edit</small>
                                </a>
                            {% endif %}
                        </h3> 
                        {% for answer in question.answer_set.all %}
                            <div class="callout {% if answer.correct %}success{% endif %}">{{ answer.text }}
                        {% empty %}
                            <p>No answers yet for this question</p>
                        {% endfor %}
                    </li>
                {% endfor %}
            </ul>
        </article>
        <hr>
        {% if user.is_authenticated %}
            <a href="{% url 'courses:edit_quiz' course_pk=step.course_id step_pk=step.pk %}" class="button">Edit Quiz</a>
            <a href="{% url 'courses:create_question' quiz_pk=step.pk question_type="mc" %}" class="button">New Multiple Choice</a>
            <a href="{% url 'courses:create_question' quiz_pk=step.pk question_type="tf" %}" class="button">New True/False</a>
        {% endif %}
    </div>
{% endblock %}

courses/templates/courses/quiz_form.html
{% extends "courses/layout.html" %}

{% block title %} {{ form.instance.title |default:"New Quiz" }} | {{ course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:course_detail' pk=course.pk %}">{{ course.title }}</a></li>
{% endblock %}

{% block content %}
<div class="row columns">
    {{ block.super }}
    <h1>{{ form.instance.title|default:"Make a new quiz" }}</h1>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="button" value="Save">
    </form>
</div>
{% endblock %}

courses/templates/courses/step_detail.html
{% extends 'base.html' %}
{% load course_extras %}

{% block title %}
    {{ step.title }}-{{ step.course.title }}
{% endblock %}

{% block content %}
    <article>
        <h2>
            <a href="{% url 'courses:course_detail' step.course.pk %}">{{ step.course.title }}</a>
        </h2>
        <h3>{{ step.title }}: <small>{{ step.description }}</small></h3>

        {% with cont=step.content %}  <!--step.content-->
            {{ cont|linebreaks }} Content: {{ cont|wordcount }} words. 
            Estimated time to complete: {{ cont|wordcount|time_estimate }} minute{{ cont|wordcount|time_estimate|pluralize }}
        {% endwith %}
    </article>
{% endblock %}

courses/templates/courses/text_detail.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}{{ step.title }} | {{ step.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:course_detail' pk=step.course.pk %}">{{ step.course.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row columns">
        <article>
            {{ block.super }}
            <h1>{{ step.title }}</h1>
            {{ step.content|markdown_to_html }}
        </article>
    </div>
{% endblock %}