courses/urls.py
from django.urls import path, re_path


from .views import (course_list, course_detail, text_detail, quiz_detail,
                    quiz_create, quiz_edit, create_question, edit_question,
                    answer_question, courses_by_teacher, search_courses)

urlpatterns = [
    path('', course_list, name='course_list'),
    re_path(r'by/(?P<teacher>[-\w]+)/$', courses_by_teacher, name='courses_by_teacher'),
    path('<int:pk>', course_detail, name='course_detail'),
    # path('<int:course_pk>/steps/<int:step_pk>', step_detail, name='step_detail'),
    path(r'search/', search_courses, name="search_courses"),
    path('<int:course_pk>/texts/<int:step_pk>', text_detail, name='text_detail'),
    path('<int:course_pk>/quizzes/<int:step_pk>', quiz_detail, name='quiz_detail'),
    path('<int:course_pk>/create_quiz', quiz_create, name='create_quiz'),
    path('<int:course_pk>/edit_quiz/<int:step_pk>', quiz_edit, name='edit_quiz'),
    re_path(r'^(?P<quiz_pk>\d+)/create_question/(?P<question_type>mc|tf)/$',
            create_question, name="create_question"),
    re_path(r'^(?P<quiz_pk>\d+)/edit_question/(?P<question_pk>\d+)/$',
            edit_question, name="edit_question"),
    re_path(r'^(?P<question_pk>\d+)/answer_question/$',
            answer_question, name="answer_question"),
]

learning_site/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('courses/', include(('courses.urls', 'courses'), namespace='courses')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += re_path(r'^__debug__/', include(debug_toolbar.urls)),

urlpatterns += staticfiles_urlpatterns()

templates/base.html
<!doctype html>
{% load static from staticfiles %}
{% load course_extras %}

<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/layout.css' %}">
        {% block css %}{% endblock %}
        <script src="{% static 'js/vendor/modernizr.js' %}"></script>
        <meta class="foundation-mq">
    </head>
    <body>
        <nav class="top-bar" role="navigation">
            <section class="top-bar-left">
                <ul class="dropdown menu" data-dropdown-menu role="menubar">
                    <li class="menu-text">The Learning Site</li>
                    <li class="has-submenu">
                        <a href="#">Courses</a>
                        <ul class="submenu menu vertical" data-submenu role="menu">
                            {% nav_courses_list %}
                            <li><a href="{% url 'courses:course_list' %}">See all &rarr;</a></li>
                        </ul>
                    </li>
                </ul>
            </section>
            <section class="top-bar-right">
                <form action="{% url 'courses:search_courses' %}" method="GET">
                    <ul class="menu">
                        <li><input type="search" name="q"></li>
                        <li><button type="button" class="secondary small button">Search</button></li>
                    </ul>
                </form>
            </section>
        </nav>
        {% if messages %}
            <div class="row">
                <div class="small-6 small-centered columns">
                    {% for message in messages %}
                        <div data-alert class="callout {{ message.tags }}">
                            {{ message }}
                            <a href="#" class="close">&times;</a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        {% block content %}{% endblock %}
        <footer class="row columns">
            <hr/>
            <div class="small-6 columns">
                <p>&copy; The Learning Site</p>
            </div>
            <div class="small-6 columns">
                <ul class="inline-list no-bullet float-right">
                    <li><a href="{% url 'courses:course_list' %}">Courses</a></li>
                </ul>
            </div>
        </footer>
        <script src="{% static 'js/vendor/jquery-2.1.4.min.js' %}"></script>
        <script src="{% static 'js/vendor/what-input.min.js' %}"></script>
        <script src="{% static 'js/foundation.min.js' %}"></script>
        {% block javascript %}{% endblock %}
        <script>$(document).foundation();</script>
    </body>
</html>